import FuiInputComp from '@/components/fui-input/fui-input.uvue'

export default {
	components: {
		FuiInputComp
	},
	data() {
		return {
			account: null, // 账号
			password: null, // 密码
		}
	},
	methods: {
		onRegister() {
			uni.navigateTo({
				url: '/pages/register/index'
			})
		},
		// 登录
		onLogin() {
			uni.request({
				url: "http://localhost:3000/api/login",
				success(res) {
					console.log(res);
				},
				fail(err) {
					console.log(err)
				}
			})
		}
	},
}