import FuiInputComp from '@/components/fui-input/fui-input.uvue'
import { drawCaptcha } from '@/utils/utils.uts'
import FuiButtonComp from "@/components/fui-button/fui-button.uvue"

export default {
	components: {
		FuiInputComp,
		FuiButtonComp
	},
	data() {
		return {
			isLoading: false
		}
	},
	methods: {
		// 更换验证码
		onChangeCode() {
			drawCaptcha('canvas', 200, 85, 45)
		}
	},
	onReady() {
		drawCaptcha('canvas', 200, 85, 45)
	}
}